Refactor system-update to zodate all config projects

diff --git a/modules/files/util-bins/system-update b/modules/files/util-bins/system-update
--- a/modules/files/util-bins/system-update
+++ b/modules/files/util-bins/system-update
@@ -1,6 +1,10 @@
 #!/usr/bin/env bash
 set -e
 
+available() {
+    hash "${1}" > /dev/null 2>&1
+}
+
 get_sudo_prefix() {
     if ! is_root; then
         echo "sudo"
@@ -9,6 +13,10 @@ get_sudo_prefix() {
 
 has_unit_enabled() {
     [[ "$(systemctl is-enabled "${1}" 2> /dev/null)" == "enabled" ]]
+}
+
+is_nixos() {
+    [[ -f "/etc/NIXOS" ]]
 }
 
 is_root() {
@@ -23,12 +31,32 @@ log() {
     echo
 }
 
-
-update_apt() {
-    if ! hash apt > /dev/null 2>&1; then
-        return
+pull_changes() {
+    if [[ -d "${2}" && -w "${2}" ]]; then
+        log "pull changes" "update ${1} project"
+        git -C "${2}" pull --prune
     fi
+}
 
+pull_changes_ssh() {
+    local ssh_path="modules/secrets/ssh/modules"
+
+    if [[ -d "${1}/${ssh_path}" ]]; then
+        for ssh_module in "${1}/${ssh_path}/"*; do
+            pull_changes "ssh $(basename "${ssh_module}")" "${ssh_module}"
+        done
+    fi
+}
+
+# add key
+if available keychain; then
+    log "keychain" "add key"
+    keychain "${HOME}/.ssh/modules/vcs/keys/id_rsa.vcs"
+fi
+
+
+# update ubuntu
+if available apt; then
     local sudo_prefix="$(get_sudo_prefix)"
 
     log "apt" "update"
@@ -39,60 +67,60 @@ update_apt() {
     "${sudo_prefix}" apt autoclean -y
     log "apt" "autoremove"
     "${sudo_prefix}" apt autoremove -y
-}
+fi
 
-update_dotfiles() {
-    if ! hash dotfiles-update > /dev/null 2>&1; then
-        return
-    fi
+if available snap && $(snap list > /dev/null 2>&1); then
+    log "snap" "refresh"
+    "$(get_sudo_prefix)" snap refresh
+fi
 
-    if hash keychain > /dev/null 2>&1; then
-        log "dotfiles" "add key"
-        keychain "${HOME}/.ssh/modules/vcs/keys/id_rsa.vcs"
-    fi
 
-    log "dotfiles" "update"
-    dotfiles-update
-}
+# update projects
+nixos="/etc/nixos"
+nixos_hm="${nixos}/home-manager-configurations"
+dotfiles="${HOME}/.dotfiles"
+dotfiles_hm="${dotfiles}/home-manager/home-manager-configurations"
 
-update_nix() {
-    if ! hash nix > /dev/null 2>&1; then
-        return
-    fi
+pull_changes "nixos"        "${nixos}"
+pull_changes "home-manager" "${nixos_hm}"
+pull_changes_ssh            "${nixos_hm}"
+pull_changes "dotfiles"     "${dotfiles}"
+pull_changes "gpg"          "${dotfiles}/gpg"
+pull_changes "home-manager" "${dotfiles_hm}"
+pull_changes_ssh            "${dotfiles_hm}"
+pull_changes "pass"         "${HOME}/.password-store"
 
-    if [[ -r "${HOME}/.nix-channels" ]] && ! has_unit_enabled "nixos-upgrade.timer" &&
-       [[ $(find /nix/var/nix/profiles/per-user -type l -iname "channels-*" -mtime -7 | wc -l) == 0 ]]; then
-        log "nix" "update nix-channel"
-        nix-channel --update
-    fi
 
-    if [[ -r "${HOME}/.nix-channels" && -r "${HOME}/.config/nixpkgs/home.nix" ]]; then
-        log "nix" "home-manager switch"
-        home-manager switch -b hm-bak
-    fi
+# nix updates
+if [[ -r "${HOME}/.nix-channels" ]] && ! has_unit_enabled "nixos-upgrade.timer" &&
+   [[ $(find /nix/var/nix/profiles/per-user -type l -iname "channels-*" -mtime -7 | wc -l) == 0 ]]; then
+    log "nix" "update nix-channel"
+    nix-channel --update
+fi
 
-    if [[ -r "${HOME}/.nix-channels" ]] && is_root; then
-        if hash keychain > /dev/null 2>&1; then
-            log "nix" "add key"
-            keychain "${HOME}/.ssh/modules/vcs/keys/id_rsa.vcs"
-        fi
+if is_nixos && is_root; then
+    log "nix" "builds nixos configuration"
+    ${nixos}/bin/rebuild build
+    log "nix" "switches nixos configuration"
+    ${nixos}/bin/rebuild switch
+fi
 
-        log "nix" "update nixos project"
-        git -C /etc/nixos pull --prune
-        log "nix" "update home-manager project"
-        git -C /etc/nixos/home-manager-configurations pull --prune
+if [[ -r "${HOME}/.config/nixpkgs/home.nix" ]] && available home-manager; then
+    log "nix" "home-manager switch"
+    home-manager switch -b hm-bak
+fi
 
-        for module in /etc/nixos/home-manager-configurations/modules/secrets/ssh/modules/*/; do
-            log "nix" "update ssh module $(basename "${module}")"
-            git -C "${module}" pull --prune
-        done
 
-         log "nix" "builds nixos configuration"
-        /etc/nixos/bin/rebuild build
-        log "nix" "switches nixos configuration"
-        /etc/nixos/bin/rebuild switch
-    fi
+# dotfiles bootstrap
+if [[ -d "${dotfiles}" ]]; then
+    log "dotfiles" "run bootstrap"
+    ${dotfiles}/bootstrap.sh
+fi
 
+
+# nix cleanup
+# no cleanup for non root users on NixOS
+if ! is_nixos || is_root; then
     if ! has_unit_enabled "nix-gc.timer"; then
         log "nix" "nix-collect-garbage"
         nix-collect-garbage --delete-older-than 14d 2> /dev/null
@@ -102,29 +130,4 @@ update_nix() {
         log "nix" "nix-store --optimise"
         nix-store --optimise
     fi
-}
-
-update_pass() {
-    if ! hash pass > /dev/null 2>&1 || is_root; then
-        return
-    fi
-
-    log "pass" "update repo"
-    pass git pull
-}
-
-update_snap() {
-    if ! hash snap > /dev/null 2>&1 || ! $(snap list > /dev/null 2>&1); then
-        return
-    fi
-
-    log "snap" "refresh"
-    "$(get_sudo_prefix)" snap refresh
-}
-
-
-update_dotfiles
-update_pass
-update_apt
-update_snap
-update_nix
+fi
